# Firebase configuration for DropBox Clone
# Service account credentials for server-side Firebase Admin
# Google service account
GOOGLE_PROJECT_ID         = "<YOUR_GOOGLE_PROJECT_ID>"
GOOGLE_PRIVATE_KEY_ID     = "<YOUR_GOOGLE_PRIVATE_KEY_ID>"
GOOGLE_PRIVATE_KEY        = """-----BEGIN PRIVATE KEY-----<YOUR_PRIVATE_KEY_CONTENT>-----END PRIVATE KEY-----"""
GOOGLE_CLIENT_EMAIL       = "<YOUR_SERVICE_ACCOUNT_EMAIL>"
GOOGLE_CLIENT_ID          = "<YOUR_GOOGLE_CLIENT_ID>"
GOOGLE_CLIENT_X509_CERT_URL = "<YOUR_X509_CERT_URL>"

# Firebase web configuration
FIREBASE_STORAGE_BUCKET     = "<YOUR_FIREBASE_STORAGE_BUCKET>"
FIREBASE_API_KEY            = "<YOUR_FIREBASE_API_KEY>"
FIREBASE_AUTH_DOMAIN        = "<YOUR_FIREBASE_AUTH_DOMAIN>"
FIREBASE_PROJECT_ID         = "<YOUR_FIREBASE_PROJECT_ID>"
FIREBASE_MESSAGING_SENDER_ID = "<YOUR_FIREBASE_MESSAGING_SENDER_ID>"
FIREBASE_APP_ID             = "<YOUR_FIREBASE_APP_ID>"
FIREBASE_MEASUREMENT_ID     = "<YOUR_FIREBASE_MEASUREMENT_ID>"
